/**
 * @file propellant_thermochemistry.h
 * @brief Reduced propellant thermochemistry and reaction-source evaluation.
 *
 * @details
 * This module converts an explicitly supplied reacted propellant mass into
 * generated gaseous-product mass, generated condensed-product mass, and
 * released reaction internal energy. It does not determine burn rate, grain
 * regression, ignition progression, gas equation-of-state behavior, mixture
 * behavior, pressure, temperature, projectile motion, or firearm safety.
 */
#ifndef BBTC_INTERNAL_BALLISTICS_PROPELLANT_THERMOCHEMISTRY_H
#define BBTC_INTERNAL_BALLISTICS_PROPELLANT_THERMOCHEMISTRY_H

#include <bbtc/status.h>

#ifdef __cplusplus
    extern "C" {
#endif

/**
 * @struct bbtc_ib_propellant_thermochemistry_float_t
 * @brief Reduced propellant thermochemistry expressed with native `float`.
 *
 * `gas_product_mass_fraction` is the fraction of reacted propellant mass
 * represented as gaseous combustion product by this reduced model. The
 * remainder is represented as condensed product.
 *
 * `specific_reaction_internal_energy_release_j_per_kg` is the positive
 * effective decrease in modeled chemical internal energy made available to a
 * later internal-ballistics energy balance per kilogram of reacted propellant.
 * It is not automatically a standard enthalpy of combustion, flame
 * temperature, propellant force/impetus, gas specific internal energy, or a
 * caloric-reference datum.
 *
 * The record contains no hidden reference temperature, pressure, gas equation
 * of state, chemical composition, ignition model, or burn-rate law.
 */
typedef struct bbtc_ib_propellant_thermochemistry_float_t
{
    /** Gaseous-product mass fraction of reacted propellant, dimensionless. */
    float gas_product_mass_fraction;

    /**
     * Effective reaction internal-energy release per reacted propellant mass,
     * in joules per kilogram.
     */
    float specific_reaction_internal_energy_release_j_per_kg;
}
bbtc_ib_propellant_thermochemistry_float_t;


/**
 * @struct bbtc_ib_propellant_thermochemistry_double_t
 * @brief Reduced propellant thermochemistry expressed with native `double`.
 *
 * Physical meaning and validation semantics match
 * `bbtc_ib_propellant_thermochemistry_float_t`.
 */
typedef struct bbtc_ib_propellant_thermochemistry_double_t
{
    /** Gaseous-product mass fraction of reacted propellant, dimensionless. */
    double gas_product_mass_fraction;

    /**
     * Effective reaction internal-energy release per reacted propellant mass,
     * in joules per kilogram.
     */
    double specific_reaction_internal_energy_release_j_per_kg;
}
bbtc_ib_propellant_thermochemistry_double_t;


/**
 * @struct bbtc_ib_propellant_thermochemistry_long_double_t
 * @brief Reduced propellant thermochemistry expressed with native `long double`.
 *
 * Physical meaning and validation semantics match the other scalar families.
 * This type does not assume that `long double` is wider than `double`.
 */
typedef struct bbtc_ib_propellant_thermochemistry_long_double_t
{
    /** Gaseous-product mass fraction of reacted propellant, dimensionless. */
    long double gas_product_mass_fraction;

    /**
     * Effective reaction internal-energy release per reacted propellant mass,
     * in joules per kilogram.
     */
    long double specific_reaction_internal_energy_release_j_per_kg;
}
bbtc_ib_propellant_thermochemistry_long_double_t;


/**
 * @struct bbtc_ib_propellant_thermochemical_source_float_t
 * @brief Extensive source terms generated by reacted propellant in native float.
 *
 * The two product masses partition only the supplied reacted propellant mass.
 * They do not include unreacted propellant, initial trapped gas, projectile
 * mass, case mass, or any later material exchange.
 */
typedef struct bbtc_ib_propellant_thermochemical_source_float_t
{
    /** Generated gaseous-product mass, in kilograms. */
    float gas_product_mass_kg;

    /** Generated condensed-product mass, in kilograms. */
    float condensed_product_mass_kg;

    /** Released reaction internal energy, in joules. */
    float reaction_internal_energy_release_j;
}
bbtc_ib_propellant_thermochemical_source_float_t;


/**
 * @struct bbtc_ib_propellant_thermochemical_source_double_t
 * @brief Extensive source terms generated by reacted propellant in native double.
 *
 * Physical meaning matches
 * `bbtc_ib_propellant_thermochemical_source_float_t`.
 */
typedef struct bbtc_ib_propellant_thermochemical_source_double_t
{
    /** Generated gaseous-product mass, in kilograms. */
    double gas_product_mass_kg;

    /** Generated condensed-product mass, in kilograms. */
    double condensed_product_mass_kg;

    /** Released reaction internal energy, in joules. */
    double reaction_internal_energy_release_j;
}
bbtc_ib_propellant_thermochemical_source_double_t;


/**
 * @struct bbtc_ib_propellant_thermochemical_source_long_double_t
 * @brief Extensive source terms generated by reacted propellant in native long double.
 *
 * Physical meaning matches the other scalar families.
 */
typedef struct bbtc_ib_propellant_thermochemical_source_long_double_t
{
    /** Generated gaseous-product mass, in kilograms. */
    long double gas_product_mass_kg;

    /** Generated condensed-product mass, in kilograms. */
    long double condensed_product_mass_kg;

    /** Released reaction internal energy, in joules. */
    long double reaction_internal_energy_release_j;
}
bbtc_ib_propellant_thermochemical_source_long_double_t;


/**
 * @brief Validates one native-float reduced propellant-thermochemistry record.
 *
 * A null pointer returns `BBTC_STATUS_INVALID_ARGUMENT`. A NaN in either field
 * returns `BBTC_STATUS_NAN_INPUT`. Otherwise, positive or negative infinity
 * returns `BBTC_STATUS_NONFINITE_INPUT`. The gaseous-product mass fraction must
 * satisfy `0 < y_g <= 1`, and the specific reaction internal-energy release
 * must be strictly positive. Finite values outside those domains return
 * `BBTC_STATUS_OUTSIDE_DOMAIN`. When both fields are nonfinite, NaN takes
 * precedence over infinity within this record.
 *
 * @param thermochemistry Caller-owned thermochemistry record to validate.
 *
 * @return `BBTC_STATUS_SUCCESS` when the record is valid; otherwise the status
 *         described above.
 */
bbtc_status_e
bbtc_ib_propellant_thermochemistry_validate_float(
    const bbtc_ib_propellant_thermochemistry_float_t* thermochemistry
);


/**
 * @brief Validates one native-double reduced propellant-thermochemistry record.
 *
 * Validation semantics match
 * `bbtc_ib_propellant_thermochemistry_validate_float()`.
 *
 * @param thermochemistry Caller-owned thermochemistry record to validate.
 *
 * @return `BBTC_STATUS_SUCCESS` when the record is valid; otherwise a nonzero
 *         validation status.
 */
bbtc_status_e
bbtc_ib_propellant_thermochemistry_validate_double(
    const bbtc_ib_propellant_thermochemistry_double_t* thermochemistry
);


/**
 * @brief Validates one native-long-double reduced thermochemistry record.
 *
 * Validation semantics match
 * `bbtc_ib_propellant_thermochemistry_validate_float()`.
 *
 * @param thermochemistry Caller-owned thermochemistry record to validate.
 *
 * @return `BBTC_STATUS_SUCCESS` when the record is valid; otherwise a nonzero
 *         validation status.
 */
bbtc_status_e
bbtc_ib_propellant_thermochemistry_validate_long_double(
    const bbtc_ib_propellant_thermochemistry_long_double_t* thermochemistry
);


/**
 * @brief Evaluates reduced reaction source terms with native `float`.
 *
 * @details
 * For reacted propellant mass `m_r`, gaseous-product fraction `y_g`, and
 * specific reaction internal-energy release `q_r`, this evaluator computes:
 *
 * `m_g = y_g * m_r`
 *
 * `m_c = (1 - y_g) * m_r`
 *
 * `Q_r = q_r * m_r`
 *
 * Zero reacted mass is a valid identity state and returns a completely zeroed
 * source record. Positive reacted mass requires positive finite gaseous-product
 * mass and reaction-energy release. When `y_g < 1`, positive finite condensed
 * product mass is also required. Unrepresentable required outputs return
 * `BBTC_STATUS_NUMERICAL_FAILURE`; values are never clamped.
 *
 * Once `result` is known to be nonnull, it is cleared before model or scalar
 * validation so every subsequent failure leaves a deterministic zero result.
 *
 * @param thermochemistry Reduced propellant thermochemistry.
 * @param reacted_propellant_mass_kg Reacted propellant mass, in kilograms.
 * @param result Caller-owned source-result record.
 *
 * @return `BBTC_STATUS_SUCCESS` on successful source evaluation; otherwise a
 *         validation or numerical-failure status.
 */
bbtc_status_e
bbtc_ib_propellant_thermochemical_source_evaluate_float(
    const bbtc_ib_propellant_thermochemistry_float_t* thermochemistry,
    float reacted_propellant_mass_kg,
    bbtc_ib_propellant_thermochemical_source_float_t* result
);


/**
 * @brief Evaluates reduced reaction source terms with native `double`.
 *
 * Equations, failure ordering, ownership, and zero-mass semantics match
 * `bbtc_ib_propellant_thermochemical_source_evaluate_float()`.
 *
 * @param thermochemistry Reduced propellant thermochemistry.
 * @param reacted_propellant_mass_kg Reacted propellant mass, in kilograms.
 * @param result Caller-owned source-result record.
 *
 * @return `BBTC_STATUS_SUCCESS` on successful source evaluation; otherwise a
 *         validation or numerical-failure status.
 */
bbtc_status_e
bbtc_ib_propellant_thermochemical_source_evaluate_double(
    const bbtc_ib_propellant_thermochemistry_double_t* thermochemistry,
    double reacted_propellant_mass_kg,
    bbtc_ib_propellant_thermochemical_source_double_t* result
);


/**
 * @brief Evaluates reduced reaction source terms with native `long double`.
 *
 * Equations, failure ordering, ownership, and zero-mass semantics match
 * `bbtc_ib_propellant_thermochemical_source_evaluate_float()`.
 *
 * @param thermochemistry Reduced propellant thermochemistry.
 * @param reacted_propellant_mass_kg Reacted propellant mass, in kilograms.
 * @param result Caller-owned source-result record.
 *
 * @return `BBTC_STATUS_SUCCESS` on successful source evaluation; otherwise a
 *         validation or numerical-failure status.
 */
bbtc_status_e
bbtc_ib_propellant_thermochemical_source_evaluate_long_double(
    const bbtc_ib_propellant_thermochemistry_long_double_t* thermochemistry,
    long double reacted_propellant_mass_kg,
    bbtc_ib_propellant_thermochemical_source_long_double_t* result
);

#ifdef __cplusplus
}   /* extern "C" */
#endif
#endif /* BBTC_INTERNAL_BALLISTICS_PROPELLANT_THERMOCHEMISTRY_H */
